name: Project autofill (simple)

on:
  issues:        { types: [opened, labeled] }
  pull_request:  { types: [opened, labeled, ready_for_review] }

permissions:
  contents: read
  issues: write
  pull-requests: write
  # Project access comes from PAT in PROJECT_TOKEN

jobs:
  autofill:
    runs-on: ubuntu-latest
    env:
      PROJECT_URL: https://github.com/users/moligarch/projects/5

    steps:
      # 1) Add item to your Project (gets itemId)
      - name: Add to Project
        id: add
        uses: actions/add-to-project@v1
        with:
          project-url: ${{ env.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_TOKEN }}

      # 2) Derive Project field values from labels
      - name: Derive fields from labels
        id: fields
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            jq -r '.issue.labels[].name' "$GITHUB_EVENT_PATH" > labels.txt
          else
            jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH" > labels.txt
          fi

          keys=(); vals=()
          add() { keys+=("$1"); vals+=("$2"); }
          while read -r lbl; do
            case "$lbl" in
              phase:*)    add "Phase"    "${lbl#*:}";;
              module:*)   add "Module"   "${lbl#*:}";;
              type:*)     add "Type"     "${lbl#*:}";;
              priority:*) add "Priority" "${lbl#*:}";;
            esac
          done < labels.txt

          if [ "${#keys[@]}" -eq 0 ]; then
            echo "field_keys=" >> "$GITHUB_OUTPUT"
            echo "field_values=" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          IFS=,; echo "field_keys=${keys[*]}"   >> "$GITHUB_OUTPUT"
          IFS=,; echo "field_values=${vals[*]}" >> "$GITHUB_OUTPUT"

      # 3) Update those fields on the Project item
      - name: Update Project fields
        if: ${{ steps.fields.outputs.field_keys != '' }}
        uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: ${{ env.PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_TOKEN }}
          item-id: ${{ steps.add.outputs.itemId }}
          field-keys: ${{ steps.fields.outputs.field_keys }}
          field-values: ${{ steps.fields.outputs.field_values }}
